# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
os:
  - linux
r:
  - release
  - devel 

r_packages:
  - covr
  - mockery
  - shinytest
  - testthat

addons:
  apt:
    update: true
    sources:
      - sourceline: 'ppa:cran/imagemagick' 
    packages:
      - libtiff-dev
      - libpng-dev
      - libjpeg-dev
      - libfftw3-dev
      - libmagick++-dev
      - librsvg2-dev
      - libwebp-dev
      - libpoppler-cpp-dev
      - libtesseract-dev
      - libleptonica-dev
      - tesseract-ocr-eng
      - r-cran-rgdal
      - libfftw3-dev
      - cargo

cache: packages

after_success:
  - Rscript -e 'covr::codecov()'
  
env:
  global:
    - _R_CHECK_DONTTEST_EXAMPLES_=FALSE